import { chromium } from 'playwright';
const BASE='http://127.0.0.1:4599/chezakvest-preview';
const b=await chromium.launch();
const p=await (await b.newContext({viewport:{width:1440,height:900}})).newPage();
await p.goto(BASE+'/kvest_v_realnosti_sherlock_holms/',{waitUntil:'load'});await p.waitForTimeout(2600);
await p.evaluate(()=>{window.__ev=[];['pointerdown','pointerup','click'].forEach(t=>document.addEventListener(t,e=>{window.__ev.push(t+' -> '+(e.target.tagName)+'.'+String(e.target.className).slice(0,40)+' def='+e.defaultPrevented);},true));
  const s=document.querySelectorAll('.t1196__slider')[1];
  window.__cap = { hasCapture: null };
  s.addEventListener('gotpointercapture',()=>{window.__ev.push('GOTPOINTERCAPTURE on slider');},true);
});
const card = p.locator('.t1196__item[href]').nth(1);
await card.scrollIntoViewIfNeeded(); await p.waitForTimeout(500);
await card.click();
await p.waitForTimeout(800);
console.log((await p.evaluate(()=>window.__ev)).join('\n'));
await b.close();
