import { chromium } from 'playwright';
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:1440,height:900}});
const p=await ctx.newPage();
const cdp=await ctx.newCDPSession(p);
await cdp.send('DOM.enable'); await cdp.send('Runtime.enable');
await p.goto('https://xn--80aehcht5ci1b.xn--p1ai/',{waitUntil:'domcontentloaded',timeout:90000});
await p.waitForTimeout(8000);
const {result}=await cdp.send('Runtime.evaluate',{expression:"document.querySelector('.t-slds__item_active .t604__imgwrapper')"});
const objId=result.objectId;
const l=await cdp.send('DOMDebugger.getEventListeners',{objectId:objId, depth:-1, pierce:true});
console.log(JSON.stringify(l.listeners.map(x=>({type:x.type, url:x.scriptId&&x.handler? '':'', ...x})),null,1).slice(0,3000));
await b.close();
