const {chromium}=require('playwright');
const OUT='/home/claude/che_za_kvest/work/tester-report/evidence/form-fields/';
(async()=>{
 const b=await chromium.launch();
 const p=await b.newPage({viewport:{width:1440,height:900}});
 await p.goto('http://127.0.0.1:4599/chezakvest-preview/',{waitUntil:'networkidle'});
 await p.waitForTimeout(3000);
 const sel='form[name="form1144740346"]';
 await p.locator(sel).scrollIntoViewIfNeeded();
 await p.waitForTimeout(500);
 await p.locator(sel+' input.t-input-phonemask').fill('asdf!!!123');
 await p.locator(sel+' input[name="name"]').fill('фыва');
 await p.locator(sel+' input[type="checkbox"]').check({force:true});
 await p.waitForTimeout(200);
 await p.screenshot({path:OUT+'52-garbage-phone-before-submit.png'});
 await p.locator(sel+' button:has-text("Жду звонка")').click();
 await p.waitForTimeout(900);
 await p.screenshot({path:OUT+'52-garbage-phone-accepted.png'});
 const st=await p.evaluate(()=>{const f=document.querySelector('form[name="form1144740346"]');const ib=f.querySelector('.t-form__inputsbox');const h=f.querySelector('input.js-phonemask-result');return{submitted:f.dataset.submitted, hiddenPhoneValue:h?h.value:null, inputsboxHiddenAttr:ib.hidden, inputsboxDisplay:getComputedStyle(ib).display, errBoxes:[...f.querySelectorAll('.t-input-error')].map(e=>e.textContent), errorboxAll:getComputedStyle(f.querySelector('.js-errorbox-all')).display};});
 console.log('AFTER GARBAGE SUBMIT',JSON.stringify(st,null,1));
 await b.close();
})();
