import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

import {
  CUTOVER_TABLE_END,
  CUTOVER_TABLE_START,
  loadLegacyUrlMap,
  renderCutoverTable,
  renderRedirects,
} from '../migration/legacy-redirects.mjs';

async function readAuditSnapshot() {
  const snapshot = await readFile(new URL('../migration/legacy-url-audit-snapshot.csv', import.meta.url), 'utf8');
  const [header, ...paths] = snapshot.trim().split(/\r?\n/);
  assert.equal(header, 'source');
  return paths;
}

test('legacy URL map contains every audited URL and the Wednesday consolidation', async () => {
  const entries = await loadLegacyUrlMap();
  const auditedSources = await readAuditSnapshot();

  assert.equal(entries.length, 103);
  assert.equal(new Set(entries.map(({ source }) => source)).size, entries.length);
  assert.equal(auditedSources.length, 102);
  assert.equal(new Set(auditedSources).size, auditedSources.length);
  assert.deepEqual(
    entries.map(({ source }) => source).sort(),
    [...auditedSources, '/wednesday_ukradennaya_vesch'].sort(),
  );

  const wednesday = entries.find(({ source }) => source === '/wednesday_ukradennaya_vesch');
  assert.deepEqual(wednesday, {
    source: '/wednesday_ukradennaya_vesch',
    target: '/wednesday-poteryannaya-dusha',
    status: '301 + fallback',
    reason: 'Tilda captures are duplicate; consolidate on the retained Wednesday page.',
  });

  assert.deepEqual(
    entries.filter(({ status }) => status === '301 + fallback').map(({ source }) => source).sort(),
    ['/wednesday_ukradennaya_vesch'],
  );

  assert.deepEqual(
    entries.filter(({ status }) => status === '200').map(({ source }) => source).sort(),
    [
      '/amongus-land', '/igra-v-kalmara-lend', '/minecraft-lend', '/new-year',
      '/new-year-2025', '/prazdniki-pod-kluch', '/privacy', '/roblox-land',
    ],
  );
});

test('generator emits permanent redirects and never self-redirects an already published path', async () => {
  const entries = await loadLegacyUrlMap();
  const redirects = renderRedirects(entries);

  assert.match(redirects, /^# Generated by `node migration\/build_legacy_redirects\.mjs`\. Do not edit\.$/m);
  assert.match(redirects, /^\/wednesday_ukradennaya_vesch \/wednesday-poteryannaya-dusha\/ 301$/m);
  assert.doesNotMatch(redirects, /^\/privacy /m);
  assert.equal(redirects.split('\n').filter((line) => / 301$/.test(line)).length, 95);
});

test('checked-in redirect artifacts are deterministic renderings of the source map', async () => {
  const entries = await loadLegacyUrlMap();
  const [redirects, cutover] = await Promise.all([
    readFile(new URL('../public/_redirects', import.meta.url), 'utf8'),
    readFile(new URL('../docs/PRODUCTION_CUTOVER.md', import.meta.url), 'utf8'),
  ]);

  assert.equal(redirects, renderRedirects(entries));

  const start = cutover.indexOf(CUTOVER_TABLE_START);
  const end = cutover.indexOf(CUTOVER_TABLE_END);
  assert.ok(start >= 0, 'cutover document must contain the redirect-table start marker');
  assert.ok(end > start, 'cutover document must contain the redirect-table end marker');
  assert.equal(
    cutover.slice(start + CUTOVER_TABLE_START.length, end),
    `\n${renderCutoverTable(entries)}\n`,
  );
});
