server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    set $chezakvest_robots_header "noindex, nofollow";
    set $chezakvest_hsts_header "";
    include /etc/nginx/snippets/chezakvest-common.conf;
}
